.\" Process this file with
.\" groff -man -Tascii screencaster.1
.\"
.TH SCREENCASTER 1 "JULY 2013" "Jade Systems Inc" "User Manuals"
.SH NAME
screencaster \- capture screencasts
.SH SYNOPSIS
.B screencaster [-h --help -p --pause -s --start]
.SH DESCRIPTION
.B screencaster
records whatever happens in the window chosen by the user, and the audio from
the default audio input device.
.SH BUGS
See the issues log at: https://github.com/lcreid/screencaster/issues
.SH AUTHOR
Larry Reid <larry.reid@jadesystems.ca>

